# Generated by Django 4.0.5 on 2022-06-16 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=150)),
                ('to', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.TimeField()),
                ('arrival', models.TimeField()),
                ('Class', models.CharField(choices=[('first', 'first'), ('second', 'second'), ('third', 'third')], max_length=150)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.line')),
            ],
        ),
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.train')),
            ],
        ),
    ]
